name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.10','3.11']
    defaults:
      run:
        shell: bash
        working-directory: .
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt
      - run: pip install ruff mypy
      - name: pytest (FAKE)
        run: pytest -q
        env:
          BLUEPRINT_FAKE: "1"
      - run: ruff check .
      - run: mypy --version && mypy app/security.py app/mission.py app/ascent.py app/geometry2.py scripts/index_experiments.py proof/index_db.py
      - name: API smoke
        run: python scripts/api_smoke.py
