name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt
      - name: pytest (FAKE)
        run: pytest -q
        env:
          BLUEPRINT_FAKE: "1"
      - name: API smoke
        run: |
          python - <<'PY'
          import threading
          import time

          import requests
          import uvicorn

          from app.main import app


          def serve() -> None:
              uvicorn.run(app, host="127.0.0.1", port=9001, log_level="error")


          thread = threading.Thread(target=serve, daemon=True)
          thread.start()
          time.sleep(2)
          resp = requests.get("http://127.0.0.1:9001/health", timeout=5)
          print(resp.json())
          PY
        env:
          BLUEPRINT_FAKE: "1"
