name: docker-smoke
on:
  push:
  pull_request:
jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build image
        run: docker build -t blueprint-npu:ci .
      - name: Run ui
        run: docker run -d --rm -p 9030:9030 --name ui -e BLUEPRINT_FAKE=1 blueprint-npu:ci
      - name: Wait and ping
        run: |
          for i in {1..30}; do
            curl -sf http://127.0.0.1:9030/ui/health && exit 0
            sleep 1
          done
          echo "ui not ready"; exit 1
      - name: Generate artifacts
        run: curl -sf -X POST http://127.0.0.1:9030/ui/generate
      - name: List manifest
        run: curl -sf http://127.0.0.1:9030/ui/manifest | tee manifest.json
      - name: Stop
        if: always()
        run: docker rm -f ui || true
