name: qa
on: [push, pull_request]
jobs:
  validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements-ov.txt -r requirements-ml.txt
      - run: python tools/validate_outputs.py save/sessions/example.jsonl
        shell: pwsh
        continue-on-error: true
